services:
  servidor:
    build: ./servidor
    container_name: servidor-desarrollo
    ports:
      - "3000:3000"
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_NAME: arquitecturahexagonal
      DB_USER: postgres
      DB_PASSWORD: admin
    volumes:
      - ./servidor:/app
      - /app/node_modules
    extra_hosts:
      - "host.docker.internal:host-gateway"

  cliente:
    build: ./cliente
    container_name: cliente-desarrollo
    ports:
      - "5174:5173"
    volumes:
      - ./cliente:/app
      - /app/node_modules
    depends_on:
      - servidor

  mongo:
    image: mongo:latest
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data: