services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: arquitecturahexagonal
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  servidor:
    build: ./servidor
    container_name: servidor-desarrollo
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: arquitecturahexagonal
      DB_USER: postgres
      DB_PASSWORD: admin
    volumes:
      - ./servidor:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    command: node src/app.js

  cliente:
    build: ./cliente
    container_name: cliente-desarrollo
    ports:
      - "5174:5173"
    volumes:
      - ./cliente:/app
      - /app/node_modules
    depends_on:
      - servidor

volumes:
  postgres_data: